# AWS CodeBuild spec to build an Elastic Beanstalk artifact for AWS CodePipeline to deploy
version: 0.2
    
phases:   
  install:
    runtime-versions:
      dotnet: latest
      
  pre_build:
    commands:
      - echo Unit Tests Execution
      - dotnet test --test-adapter-path:. --logger:nunit --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
      - mv Books-Inventory-System.UnitTests/TestResults/**/coverage.opencover.xml Books-Inventory-System.UnitTests/TestResults
      - export SONAR_SCANNER_VERSION=4.4.0.2170
      - export SONAR_SCANNER_HOME=$HOME/.sonar/sonar-scanner-$SONAR_SCANNER_VERSION-linux
      - curl --create-dirs -sSLo $HOME/.sonar/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$SONAR_SCANNER_VERSION-linux.zip
      - unzip -o $HOME/.sonar/sonar-scanner.zip -d $HOME/.sonar/
      - export PATH=$SONAR_SCANNER_HOME/bin:$PATH
      - export SONAR_SCANNER_OPTS="-server"
      - export SONAR_TOKEN=2f591a02651773cefb90c640dcdce3ce1ce47064
      - echo Run sonar analysis
      - sonar-scanner -Dsonar.organization=aneeqanwar -Dsonar.projectKey=AneeqAnwar_dot-net-backend -Dsonar.sources=. -Dsonar.host.url=https://sonarcloud.io -Dsonar.cs.nunit.reportsPaths=$CODEBUILD_SRC_DIR/Books-Inventory-System.UnitTests/TestResults/TestResults.xml -Dsonar.cs.opencover.reportsPaths=$CODEBUILD_SRC_DIR/Books-Inventory-System.UnitTests/TestResults/coverage.opencover.xml
      - echo Restore started on `date`
      - cd Books-Inventory-System
      - dotnet restore Books-Inventory-System.csproj
      
  build:
    commands:
      - echo Build started on `date`
      - dotnet build Books-Inventory-System.csproj
      
  post_build:
    commands:
      - echo Publish started on `date`
      - dotnet publish -c Release -r linux-x64 --self-contained false Books-Inventory-System.csproj

reports:
  UnitTestsReports:
    file-format: NUNIT3XML
    files:
      - 'TestResults.xml'
    base-directory: 'Books-Inventory-System.UnitTests/TestResults/'
      
artifacts:
  files:
    - '**/*'
  base-directory: 'Books-Inventory-System/bin/Release/netcoreapp3.1/linux-x64/publish/'
  discard-paths: no