# AWS CodeBuild spec to build an Elastic Beanstalk artifact for AWS CodePipeline to deploy
version: 0.2
    
phases:   
  install:
    runtime-versions:
      dotnet: latest
      
  pre_build:
    commands:
      - echo Unit Tests Execution
      - dotnet test --test-adapter-path:. --logger:nunit --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
      - echo Restore started on `date`
      - cd Books-Inventory-System
      - dotnet restore Books-Inventory-System.csproj
      
  build:
    commands:
      - echo Build started on `date`
      - dotnet build Books-Inventory-System.csproj
      
  post_build:
    commands:
      - echo Publish started on `date`
      - dotnet publish -c Release -r linux-x64 --self-contained false Books-Inventory-System.csproj

reports:
  UnitTestsReports:
    file-format: NUNIT3XML
    files:
      - 'TestResults.xml'
    base-directory: 'Books-Inventory-System.UnitTests/TestResults/'
      
artifacts:
  files:
    - '**/*'
  base-directory: 'Books-Inventory-System/bin/Release/netcoreapp3.1/linux-x64/publish/'
  discard-paths: no