# AWS CodeBuild spec to build an Elastic Beanstalk artifact for AWS CodePipeline to deploy
version: 0.2
    
phases:   
  install:
    runtime-versions:
      dotnet: latest
      
  pre_build:
    commands:
      - echo Unit Tests Execution
      - dotnet test --test-adapter-path:. --logger:nunit
      - echo Restore started on `date`
      - ls
      - cd Books-Inventory-System
      - dotnet restore Books-Inventory-System.csproj
      
  build:
    commands:
      - echo Build started on `date`
      - dotnet build Books-Inventory-System.csproj
      
  post_build:
    commands:
      - echo Publish started on `date`
      - dotnet publish -c Release -r linux-x64 --self-contained false Books-Inventory-System.csproj
      - ls -R

reports:
  UnitTestsReports:
    files:
      - '**/*'
    base-directory: 'Books-Inventory-System.UnitTests/TestResults/TestResults.xml'
      
artifacts:
  files:
    - '**/*'
  base-directory: 'Books-Inventory-System/bin/Release/netcoreapp3.1/linux-x64/publish/'
  discard-paths: no